const JsonData = [
  {
    page: "Page1",
    Data: [
      {
        component: "Title",
        font_size: "40px",
        margin: "10px 0",
        color: "black",
        text_align: "left",
        content: "Water Management",
      },
      {
        component: "Heading",
        font_size: "30px",
        margin: "10px 0",
        color: "black",
        content: "Conservation Techniques",
      },
      {
        component: "Description",
        font_size: "15px",
        margin: "5px 0",
        color: "black",
        text_align: "left",
        content:
          "Water management involves planning, developing, and managing water resources effectively. It includes practices such as rainwater harvesting, watershed management, and sustainable irrigation methods.",
      },
      {
        component: "Section",
        display: "flex",
        align_items: "center",
        justify_content: "space-evenly",
        height: "300px",
        width: "100%",
        margin: "15px 0",
        child_components: [
          {
            component: "Sub-Section",
            display: "flex",
            align_items: "left",
            justify_content: "center",
            flex_direction: "column",
            padding: "0 15px",
            height: "100%",
            width: "200px",
            contents: [
              {
                component: "Sub-Heading",
                font_size: "20px",
                margin: "10px 0",
                color: "black",
                content: "Rainwater Harvesting",
              },
              {
                component: "Description",
                font_size: "15px",
                margin: "5px 0",
                color: "black",
                text_align: "left",
                content:
                  "Collecting and storing rainwater for reuse before it reaches the aquifer.",
              },
            ],
          },
          {
            component: "Sub-Section",
            display: "flex",
            align_items: "left",
            justify_content: "center",
            flex_direction: "column",
            padding: "0 15px",
            height: "100%",
            width: "200px",
            contents: [
              {
                component: "Sub-Heading",
                font_size: "20px",
                margin: "10px 0",
                color: "black",
                content: "Watershed Management",
              },
              {
                component: "Image",
                display: "flex",
                align_items: "center",
                justify_content: "center",
                image_link: "./Images/Screenshots_PPT/Xebia_logo.png",
                height: "150px",
                width: "150px",
              },
            ],
          },
          {
            component: "Sub-Section",
            display: "flex",
            align_items: "left",
            justify_content: "center",
            flex_direction: "column",
            padding: "0 15px",
            height: "100%",
            width: "200px",
            contents: [
              {
                component: "Sub-Heading",
                font_size: "20px",
                margin: "10px 0",
                color: "black",
                content: "Smart Irrigation",
              },
              {
                component: "Bullet-Points",
                margin: "0px 0px",
                li: {
                  font_size: "15px",
                  color: "black",
                },
                points: [
                  "Drip systems",
                  "Sensors & timers",
                  "Efficient water usage",
                  "Benefits:",
                ],
              },
            ],
          },
          {
            component: "Sub-Section",
            display: "flex",
            align_items: "left",
            justify_content: "center",
            flex_direction: "column",
            padding: "0 15px",
            height: "100%",
            width: "200px",
            contents: [
              {
                component: "Sub-Heading",
                font_size: "20px",
                margin: "10px 0",
                color: "black",
                content: "Greywater Recycling",
              },
              {
                component: "Description",
                font_size: "15px",
                margin: "5px 0",
                color: "black",
                text_align: "left",
                content:
                  "Reusing wastewater from sinks, showers, and washing machines for gardening and flushing.",
              },
            ],
          },
        ],
      },
    ],
  },
];